# Generated by Django 3.2.8 on 2022-01-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=12)),
                ('Desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachername', models.CharField(max_length=122)),
                ('Teacherpwd', models.CharField(max_length=12)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forAA', to='home.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=122)),
                ('Spwd', models.CharField(max_length=12)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forA', to='home.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=100)),
                ('Afile', models.FileField(upload_to='media')),
                ('Teachername', models.CharField(max_length=100)),
                ('Notice', models.CharField(max_length=200, null=True)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forAAA', to='home.classroom')),
            ],
        ),
    ]
