# Generated by Django 3.2.8 on 2022-01-15 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_assignment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=100)),
                ('Sfile', models.FileField(upload_to='media')),
                ('studentname', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign', to='home.classroom')),
            ],
        ),
    ]
