# Generated by Django 3.2.8 on 2022-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_stuassign_sfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuassign',
            name='Sfile',
            field=models.FileField(null=True, upload_to='submissions'),
        ),
    ]
